// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI69TFe7XJ1VfJDthwTUAWwZYOFVPhM2s',
    appId: '1:257730270312:web:35efdf732fe340f5f297dd',
    messagingSenderId: '257730270312',
    projectId: 'flutter-prep-c705c',
    authDomain: 'flutter-prep-c705c.firebaseapp.com',
    databaseURL: 'https://flutter-prep-c705c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-c705c.firebasestorage.app',
    measurementId: 'G-1FZ30PLVEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS7UuQcAlkDCuyjcY84MLFSFz6a3dLpL4',
    appId: '1:257730270312:android:75557b7485fc01dbf297dd',
    messagingSenderId: '257730270312',
    projectId: 'flutter-prep-c705c',
    databaseURL: 'https://flutter-prep-c705c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-c705c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj4Nzwo44W4TD0YM1u4QvpFCQM6ottSkg',
    appId: '1:257730270312:ios:b4175eaad6a85441f297dd',
    messagingSenderId: '257730270312',
    projectId: 'flutter-prep-c705c',
    databaseURL: 'https://flutter-prep-c705c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-c705c.firebasestorage.app',
    iosBundleId: 'com.example.cicdTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI69TFe7XJ1VfJDthwTUAWwZYOFVPhM2s',
    appId: '1:257730270312:web:2822450baef89f22f297dd',
    messagingSenderId: '257730270312',
    projectId: 'flutter-prep-c705c',
    authDomain: 'flutter-prep-c705c.firebaseapp.com',
    databaseURL: 'https://flutter-prep-c705c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-c705c.firebasestorage.app',
    measurementId: 'G-86JCFG4QB0',
  );
}
