name: Flutter CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build and Export iOS using Fastlane
        run: fastlane build_and_export
        working-directory: ios/

      - name: Upload iOS IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          path: ios/build/Runner.ipa
